### ISSUE TITLE
Jira Cloud: Error : TypeError: Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by AymDev** [marc0l92/joplin-plugin-jira-tag#23]
Hi,
The company I work with recently switched to Jira Cloud. I changed my authentication method to API token but I now get the following error:
>Error :
TypeError: Cannot read properties of undefined (reading 'join')

Do you have any idea about what is going wrong ?
Maybe I can share anonymized REST API response if you need to see the JSON structure.

Thank you for this great plugin.

**Comment by marc0l92** [comment]
Please open the console with Ctrl+Shift+i and send me a screenshot o the full error stack.
You should be able to see something like this:

![image](https://github.com/marc0l92/joplin-plugin-jira-issue/assets/12623073/fb7d01b8-6b3e-43ce-bc4e-7941823c5d00)

**Comment by AymDev** [comment]
There is no error in the console, I only get this message logged when I open a note or change the issue key:
![image](https://github.com/marc0l92/joplin-plugin-jira-issue/assets/22072016/0d4fd0ae-46f5-41c2-9135-68fc25c18645)

**Comment by jtyszkiew** [comment]
+1, any update on this one? :) It's cool plugin, would love to use it with jira cloud.
---
Edit: After investigation here: https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/#simple-example it seems that jira accepts username:api_key as basic auth credentials, and after test it works fine - maybe this will help someone :)

**Comment by AymDev** [comment]
I finally made it work, just by using the email address as the username and the API token as the password. I'm surprised I didn't try it earlier...
Thanks !
